/**
 * Do not edit directly
 * Generated on Mon, 11 Jul 2022 09:18:14 GMT
 */

export const TokenGray0 = "#fcfcfc";
export const TokenGray50 = "#e9e9e9";
export const TokenGray100 = "#c8c8c8";
export const TokenGray200 = "#b0b0b1";
export const TokenGray300 = "#979899";
export const TokenGray400 = "#74797d";
export const TokenGray500 = "#67686b";
export const TokenGray600 = "#4e5053";
export const TokenGray700 = "#1e2025";
export const TokenGray800 = "#0d121c";
export const TokenGray900 = "#06080e";
export const TokenSurfaceBlackout = "#00000066";
export const TokenSurfaceBack = "#e3e5e8";
export const TokenSurfaceMid = "#f2f3f5";
export const TokenSurfaceFront = "#fafafa";
export const TokenInteractiveLight = "#e6eeff";
export const TokenInteractiveLightHover = "#b4cdff";
export const TokenInteractiveDefault = "#689aff";
export const TokenInteractiveHover = "#457ef0";
export const TokenValidationSuccessMain = "#45f067";
export const TokenValidationSuccessBg = "#e7faeb";
export const TokenValidationSuccessContent = "#0d6b23";
export const TokenValidationWarningMain = "#f2bd04";
export const TokenValidationWarningBg = "#fff8cb";
export const TokenValidationWarningContent = "#673c09";
export const TokenValidationErrorMain = "#f04b45";
export const TokenValidationErrorBg = "#fbedef";
export const TokenValidationErrorContent = "#951a20";
export const TokenHeatStatusBlue = "#94aaaf";
export const TokenHeatStatusBlueAlpha = "#b4ceff70";
export const TokenHeatStatusGreen = "#45f067";
export const TokenHeatStatusGreenAlpha = "#45f06770";
export const TokenHeatStatusYellow = "#f0bc03";
export const TokenHeatStatusYellowAlpha = "#f0bc0370";
export const TokenHeatStatusRed = "#f04b45";
export const TokenHeatStatusRedAlpha = "#f04b4570";
export const TokenMacroRegionPink = "#ee2d62";
export const TokenMacroRegionPinkAlpha = "#ee2d6299";
export const TokenMacroRegionOrange = "#f8931f";
export const TokenMacroRegionOrangeAlpha = "#f8931f99";
export const TokenMacroRegionDarkGreen = "#45a040";
export const TokenMacroRegionDarkGreenAlpha = "#45a04099";
export const TokenMacroRegionBlue = "#4ec6df";
export const TokenMacroRegionBlueAlpha = "#4ec6df99";
export const TokenMacroRegionOutlinePink = "#f986a5";
export const TokenMacroRegionOutlineOrange = "#f6ce9e";
export const TokenMacroRegionOutlineDarkGreen = "#54ed76";
export const TokenMacroRegionOutlineBlue = "#b8ebf5";